# Generated by Django 2.1.2 on 2018-12-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='surfer',
            new_name='user',
        ),
    ]
