# Generated by Django 2.1.3 on 2018-12-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='article',
        ),
        migrations.AddField(
            model_name='notification',
            name='article',
            field=models.ManyToManyField(to='notifications.Article'),
        ),
    ]
