# Generated by Django 2.1.3 on 2018-12-18 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likesdislike',
            name='article',
            field=models.ManyToManyField(to='articles.Article'),
        ),
        migrations.AddField(
            model_name='likesdislike',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='highlight',
            name='article',
            field=models.ManyToManyField(to='articles.Article'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritearticle',
            name='article',
            field=models.ManyToManyField(to='articles.Article'),
        ),
        migrations.AddField(
            model_name='favoritearticle',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commenthistory',
            name='article',
            field=models.ManyToManyField(to='articles.Article'),
        ),
        migrations.AddField(
            model_name='commenthistory',
            name='comment',
            field=models.ManyToManyField(to='articles.Comment'),
        ),
        migrations.AddField(
            model_name='commenthistory',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ManyToManyField(to='articles.Article'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmarkedarticle',
            name='article',
            field=models.ManyToManyField(to='articles.Article'),
        ),
        migrations.AddField(
            model_name='bookmarkedarticle',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlerating',
            name='article',
            field=models.ManyToManyField(to='articles.Article'),
        ),
        migrations.AddField(
            model_name='articlerating',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='articles.Tag'),
        ),
    ]
