# Generated by Django 2.1.3 on 2018-12-19 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181219_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerating',
            name='article',
            field=models.ForeignKey(db_column='art_slug', on_delete=django.db.models.deletion.CASCADE, to='articles.Article', to_field='art_slug'),
        ),
        migrations.AlterField(
            model_name='articlerating',
            name='user',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
